---
title: "R Notebook"
output: html_notebook
---
```{r}
library(broom)
options(digits = 3)
set.seed(1234)
theme_set(theme_minimal())
```

```{r}
df <- read.csv("migration_data.csv")
```

Creating differences in variables
```{r}
df['fertility_diff_1990'] <- df['fertility_1990_y'] - df['fertility_1990_x']
df['labor_diff_1990'] <- df['laborparticipation_1990_y'] - df['laborparticipation_1990_x']
```

Running the factor regressions
```{r}
fertility_mod <- lm(value ~ fertility_diff_1990 + dummy_CAN + dummy_USA + dummy_AGO + dummy_BDI + dummy_BEN + dummy_BFA + dummy_BWA + dummy_CAF + dummy_CMR + dummy_COM + dummy_DJI + dummy_DZA + dummy_ERI + dummy_ETH + dummy_GAB + dummy_GHA + dummy_GIN + dummy_GNB + dummy_GNQ + dummy_KEN + dummy_LBR + dummy_LBY + dummy_LSO + dummy_MAR + dummy_MDG + dummy_MLI + dummy_MOZ + dummy_MRT + dummy_MUS + dummy_MWI + dummy_NAM + dummy_NER + dummy_NGA + dummy_RWA + dummy_SDN + dummy_SEN + dummy_SLE + dummy_SOM + dummy_SSD + dummy_SWZ + dummy_TCD + dummy_TGO + dummy_TUN + dummy_TZA + dummy_UGA + dummy_ZAF + dummy_ZMB + dummy_ZWE + dummy_ALB + dummy_AUT + dummy_BEL + dummy_BGR + dummy_CHE + dummy_CHI + dummy_CZE + dummy_DEU + dummy_DNK + dummy_ESP + dummy_FIN + dummy_FRA + dummy_GBR + dummy_GRC + dummy_HRV + dummy_HUN + dummy_IRL + dummy_ISL + dummy_ITA + dummy_LUX + dummy_MLT + dummy_MNE + dummy_NLD + dummy_NOR + dummy_POL + dummy_PRT + dummy_ROU + dummy_SRB + dummy_SVN + dummy_SWE + dummy_ARM + dummy_AZE + dummy_BLR + dummy_EST + dummy_GEO + dummy_KAZ + dummy_LTU + dummy_LVA + dummy_MDA + dummy_TJK + dummy_TKM + dummy_UKR + dummy_UZB + dummy_ARE + dummy_BHR + dummy_CYP + dummy_IRQ + dummy_ISR + dummy_JOR + dummy_KWT + dummy_LBN + dummy_OMN + dummy_QAT + dummy_SAU + dummy_TUR + dummy_AFG + dummy_BGD + dummy_BTN + dummy_IND + dummy_LKA + dummy_MDV + dummy_NPL + dummy_PAK + dummy_CHN + dummy_JPN + dummy_MNG + dummy_IDN + dummy_KHM + dummy_MMR + dummy_MYS + dummy_PHL + dummy_SGP + dummy_THA + dummy_TLS + dummy_VNM + dummy_AUS + dummy_FJI + dummy_GUM + dummy_NCL + dummy_NZL + dummy_PNG + dummy_PYF + dummy_SLB + dummy_TON + dummy_VUT + dummy_WSM + dummy_ABW + dummy_ARG + dummy_BLZ + dummy_BOL + dummy_BRA + dummy_BRB + dummy_CHL + dummy_COL + dummy_CRI + dummy_CUB + dummy_DOM + dummy_ECU + dummy_GRD + dummy_GTM + dummy_GUY + dummy_HND + dummy_HTI + dummy_JAM + dummy_MEX + dummy_NIC + dummy_PAN + dummy_PER + dummy_PRI + dummy_PRY + dummy_SLV + dummy_SUR + dummy_URY + dummy_1990 + dummy_1995 + dummy_2000 + dummy_2005, data = df)

labor_mod <- lm(value ~ labor_diff_1990 + dummy_CAN + dummy_USA + dummy_AGO + dummy_BDI + dummy_BEN + dummy_BFA + dummy_BWA + dummy_CAF + dummy_CMR + dummy_COM + dummy_DJI + dummy_DZA + dummy_ERI + dummy_ETH + dummy_GAB + dummy_GHA + dummy_GIN + dummy_GNB + dummy_GNQ + dummy_KEN + dummy_LBR + dummy_LBY + dummy_LSO + dummy_MAR + dummy_MDG + dummy_MLI + dummy_MOZ + dummy_MRT + dummy_MUS + dummy_MWI + dummy_NAM + dummy_NER + dummy_NGA + dummy_RWA + dummy_SDN + dummy_SEN + dummy_SLE + dummy_SOM + dummy_SSD + dummy_SWZ + dummy_TCD + dummy_TGO + dummy_TUN + dummy_TZA + dummy_UGA + dummy_ZAF + dummy_ZMB + dummy_ZWE + dummy_ALB + dummy_AUT + dummy_BEL + dummy_BGR + dummy_CHE + dummy_CHI + dummy_CZE + dummy_DEU + dummy_DNK + dummy_ESP + dummy_FIN + dummy_FRA + dummy_GBR + dummy_GRC + dummy_HRV + dummy_HUN + dummy_IRL + dummy_ISL + dummy_ITA + dummy_LUX + dummy_MLT + dummy_MNE + dummy_NLD + dummy_NOR + dummy_POL + dummy_PRT + dummy_ROU + dummy_SRB + dummy_SVN + dummy_SWE + dummy_ARM + dummy_AZE + dummy_BLR + dummy_EST + dummy_GEO + dummy_KAZ + dummy_LTU + dummy_LVA + dummy_MDA + dummy_TJK + dummy_TKM + dummy_UKR + dummy_UZB + dummy_ARE + dummy_BHR + dummy_CYP + dummy_IRQ + dummy_ISR + dummy_JOR + dummy_KWT + dummy_LBN + dummy_OMN + dummy_QAT + dummy_SAU + dummy_TUR + dummy_AFG + dummy_BGD + dummy_BTN + dummy_IND + dummy_LKA + dummy_MDV + dummy_NPL + dummy_PAK + dummy_CHN + dummy_JPN + dummy_MNG + dummy_IDN + dummy_KHM + dummy_MMR + dummy_MYS + dummy_PHL + dummy_SGP + dummy_THA + dummy_TLS + dummy_VNM + dummy_AUS + dummy_FJI + dummy_GUM + dummy_NCL + dummy_NZL + dummy_PNG + dummy_PYF + dummy_SLB + dummy_TON + dummy_VUT + dummy_WSM + dummy_ABW + dummy_ARG + dummy_BLZ + dummy_BOL + dummy_BRA + dummy_BRB + dummy_CHL + dummy_COL + dummy_CRI + dummy_CUB + dummy_DOM + dummy_ECU + dummy_GRD + dummy_GTM + dummy_GUY + dummy_HND + dummy_HTI + dummy_JAM + dummy_MEX + dummy_NIC + dummy_PAN + dummy_PER + dummy_PRI + dummy_PRY + dummy_SLV + dummy_SUR + dummy_URY + dummy_1990 + dummy_1995 + dummy_2000 + dummy_2005, data = df)

literacy_mod <- lm(value ~ literacy_1990_y + dummy_CAN + dummy_USA + dummy_AGO + dummy_BDI + dummy_BEN + dummy_BFA + dummy_BWA + dummy_CAF + dummy_CMR + dummy_COM + dummy_DJI + dummy_DZA + dummy_ERI + dummy_ETH + dummy_GAB + dummy_GHA + dummy_GIN + dummy_GNB + dummy_GNQ + dummy_KEN + dummy_LBR + dummy_LBY + dummy_LSO + dummy_MAR + dummy_MDG + dummy_MLI + dummy_MOZ + dummy_MRT + dummy_MUS + dummy_MWI + dummy_NAM + dummy_NER + dummy_NGA + dummy_RWA + dummy_SDN + dummy_SEN + dummy_SLE + dummy_SOM + dummy_SSD + dummy_SWZ + dummy_TCD + dummy_TGO + dummy_TUN + dummy_TZA + dummy_UGA + dummy_ZAF + dummy_ZMB + dummy_ZWE + dummy_ALB + dummy_AUT + dummy_BEL + dummy_BGR + dummy_CHE + dummy_CHI + dummy_CZE + dummy_DEU + dummy_DNK + dummy_ESP + dummy_FIN + dummy_FRA + dummy_GBR + dummy_GRC + dummy_HRV + dummy_HUN + dummy_IRL + dummy_ISL + dummy_ITA + dummy_LUX + dummy_MLT + dummy_MNE + dummy_NLD + dummy_NOR + dummy_POL + dummy_PRT + dummy_ROU + dummy_SRB + dummy_SVN + dummy_SWE + dummy_ARM + dummy_AZE + dummy_BLR + dummy_EST + dummy_GEO + dummy_KAZ + dummy_LTU + dummy_LVA + dummy_MDA + dummy_TJK + dummy_TKM + dummy_UKR + dummy_UZB + dummy_ARE + dummy_BHR + dummy_CYP + dummy_IRQ + dummy_ISR + dummy_JOR + dummy_KWT + dummy_LBN + dummy_OMN + dummy_QAT + dummy_SAU + dummy_TUR + dummy_AFG + dummy_BGD + dummy_BTN + dummy_IND + dummy_LKA + dummy_MDV + dummy_NPL + dummy_PAK + dummy_CHN + dummy_JPN + dummy_MNG + dummy_IDN + dummy_KHM + dummy_MMR + dummy_MYS + dummy_PHL + dummy_SGP + dummy_THA + dummy_TLS + dummy_VNM + dummy_AUS + dummy_FJI + dummy_GUM + dummy_NCL + dummy_NZL + dummy_PNG + dummy_PYF + dummy_SLB + dummy_TON + dummy_VUT + dummy_WSM + dummy_ABW + dummy_ARG + dummy_BLZ + dummy_BOL + dummy_BRA + dummy_BRB + dummy_CHL + dummy_COL + dummy_CRI + dummy_CUB + dummy_DOM + dummy_ECU + dummy_GRD + dummy_GTM + dummy_GUY + dummy_HND + dummy_HTI + dummy_JAM + dummy_MEX + dummy_NIC + dummy_PAN + dummy_PER + dummy_PRI + dummy_PRY + dummy_SLV + dummy_SUR + dummy_URY + dummy_1990 + dummy_1995 + dummy_2000 + dummy_2005, data = df)

enroll_mod <- lm(value ~ primaryenroll_1990_y + dummy_CAN + dummy_USA + dummy_AGO + dummy_BDI + dummy_BEN + dummy_BFA + dummy_BWA + dummy_CAF + dummy_CMR + dummy_COM + dummy_DJI + dummy_DZA + dummy_ERI + dummy_ETH + dummy_GAB + dummy_GHA + dummy_GIN + dummy_GNB + dummy_GNQ + dummy_KEN + dummy_LBR + dummy_LBY + dummy_LSO + dummy_MAR + dummy_MDG + dummy_MLI + dummy_MOZ + dummy_MRT + dummy_MUS + dummy_MWI + dummy_NAM + dummy_NER + dummy_NGA + dummy_RWA + dummy_SDN + dummy_SEN + dummy_SLE + dummy_SOM + dummy_SSD + dummy_SWZ + dummy_TCD + dummy_TGO + dummy_TUN + dummy_TZA + dummy_UGA + dummy_ZAF + dummy_ZMB + dummy_ZWE + dummy_ALB + dummy_AUT + dummy_BEL + dummy_BGR + dummy_CHE + dummy_CHI + dummy_CZE + dummy_DEU + dummy_DNK + dummy_ESP + dummy_FIN + dummy_FRA + dummy_GBR + dummy_GRC + dummy_HRV + dummy_HUN + dummy_IRL + dummy_ISL + dummy_ITA + dummy_LUX + dummy_MLT + dummy_MNE + dummy_NLD + dummy_NOR + dummy_POL + dummy_PRT + dummy_ROU + dummy_SRB + dummy_SVN + dummy_SWE + dummy_ARM + dummy_AZE + dummy_BLR + dummy_EST + dummy_GEO + dummy_KAZ + dummy_LTU + dummy_LVA + dummy_MDA + dummy_TJK + dummy_TKM + dummy_UKR + dummy_UZB + dummy_ARE + dummy_BHR + dummy_CYP + dummy_IRQ + dummy_ISR + dummy_JOR + dummy_KWT + dummy_LBN + dummy_OMN + dummy_QAT + dummy_SAU + dummy_TUR + dummy_AFG + dummy_BGD + dummy_BTN + dummy_IND + dummy_LKA + dummy_MDV + dummy_NPL + dummy_PAK + dummy_CHN + dummy_JPN + dummy_MNG + dummy_IDN + dummy_KHM + dummy_MMR + dummy_MYS + dummy_PHL + dummy_SGP + dummy_THA + dummy_TLS + dummy_VNM + dummy_AUS + dummy_FJI + dummy_GUM + dummy_NCL + dummy_NZL + dummy_PNG + dummy_PYF + dummy_SLB + dummy_TON + dummy_VUT + dummy_WSM + dummy_ABW + dummy_ARG + dummy_BLZ + dummy_BOL + dummy_BRA + dummy_BRB + dummy_CHL + dummy_COL + dummy_CRI + dummy_CUB + dummy_DOM + dummy_ECU + dummy_GRD + dummy_GTM + dummy_GUY + dummy_HND + dummy_HTI + dummy_JAM + dummy_MEX + dummy_NIC + dummy_PAN + dummy_PER + dummy_PRI + dummy_PRY + dummy_SLV + dummy_SUR + dummy_URY + dummy_1990 + dummy_1995 + dummy_2000 + dummy_2005, data = df)

age_mod <- lm(value ~ workingagepop_1990_y + dummy_CAN + dummy_USA + dummy_AGO + dummy_BDI + dummy_BEN + dummy_BFA + dummy_BWA + dummy_CAF + dummy_CMR + dummy_COM + dummy_DJI + dummy_DZA + dummy_ERI + dummy_ETH + dummy_GAB + dummy_GHA + dummy_GIN + dummy_GNB + dummy_GNQ + dummy_KEN + dummy_LBR + dummy_LBY + dummy_LSO + dummy_MAR + dummy_MDG + dummy_MLI + dummy_MOZ + dummy_MRT + dummy_MUS + dummy_MWI + dummy_NAM + dummy_NER + dummy_NGA + dummy_RWA + dummy_SDN + dummy_SEN + dummy_SLE + dummy_SOM + dummy_SSD + dummy_SWZ + dummy_TCD + dummy_TGO + dummy_TUN + dummy_TZA + dummy_UGA + dummy_ZAF + dummy_ZMB + dummy_ZWE + dummy_ALB + dummy_AUT + dummy_BEL + dummy_BGR + dummy_CHE + dummy_CHI + dummy_CZE + dummy_DEU + dummy_DNK + dummy_ESP + dummy_FIN + dummy_FRA + dummy_GBR + dummy_GRC + dummy_HRV + dummy_HUN + dummy_IRL + dummy_ISL + dummy_ITA + dummy_LUX + dummy_MLT + dummy_MNE + dummy_NLD + dummy_NOR + dummy_POL + dummy_PRT + dummy_ROU + dummy_SRB + dummy_SVN + dummy_SWE + dummy_ARM + dummy_AZE + dummy_BLR + dummy_EST + dummy_GEO + dummy_KAZ + dummy_LTU + dummy_LVA + dummy_MDA + dummy_TJK + dummy_TKM + dummy_UKR + dummy_UZB + dummy_ARE + dummy_BHR + dummy_CYP + dummy_IRQ + dummy_ISR + dummy_JOR + dummy_KWT + dummy_LBN + dummy_OMN + dummy_QAT + dummy_SAU + dummy_TUR + dummy_AFG + dummy_BGD + dummy_BTN + dummy_IND + dummy_LKA + dummy_MDV + dummy_NPL + dummy_PAK + dummy_CHN + dummy_JPN + dummy_MNG + dummy_IDN + dummy_KHM + dummy_MMR + dummy_MYS + dummy_PHL + dummy_SGP + dummy_THA + dummy_TLS + dummy_VNM + dummy_AUS + dummy_FJI + dummy_GUM + dummy_NCL + dummy_NZL + dummy_PNG + dummy_PYF + dummy_SLB + dummy_TON + dummy_VUT + dummy_WSM + dummy_ABW + dummy_ARG + dummy_BLZ + dummy_BOL + dummy_BRA + dummy_BRB + dummy_CHL + dummy_COL + dummy_CRI + dummy_CUB + dummy_DOM + dummy_ECU + dummy_GRD + dummy_GTM + dummy_GUY + dummy_HND + dummy_HTI + dummy_JAM + dummy_MEX + dummy_NIC + dummy_PAN + dummy_PER + dummy_PRI + dummy_PRY + dummy_SLV + dummy_SUR + dummy_URY + dummy_1990 + dummy_1995 + dummy_2000 + dummy_2005, data = df)

gdp_mod <- lm(value ~ perworkergdp_1990_y + dummy_CAN + dummy_USA + dummy_AGO + dummy_BDI + dummy_BEN + dummy_BFA + dummy_BWA + dummy_CAF + dummy_CMR + dummy_COM + dummy_DJI + dummy_DZA + dummy_ERI + dummy_ETH + dummy_GAB + dummy_GHA + dummy_GIN + dummy_GNB + dummy_GNQ + dummy_KEN + dummy_LBR + dummy_LBY + dummy_LSO + dummy_MAR + dummy_MDG + dummy_MLI + dummy_MOZ + dummy_MRT + dummy_MUS + dummy_MWI + dummy_NAM + dummy_NER + dummy_NGA + dummy_RWA + dummy_SDN + dummy_SEN + dummy_SLE + dummy_SOM + dummy_SSD + dummy_SWZ + dummy_TCD + dummy_TGO + dummy_TUN + dummy_TZA + dummy_UGA + dummy_ZAF + dummy_ZMB + dummy_ZWE + dummy_ALB + dummy_AUT + dummy_BEL + dummy_BGR + dummy_CHE + dummy_CHI + dummy_CZE + dummy_DEU + dummy_DNK + dummy_ESP + dummy_FIN + dummy_FRA + dummy_GBR + dummy_GRC + dummy_HRV + dummy_HUN + dummy_IRL + dummy_ISL + dummy_ITA + dummy_LUX + dummy_MLT + dummy_MNE + dummy_NLD + dummy_NOR + dummy_POL + dummy_PRT + dummy_ROU + dummy_SRB + dummy_SVN + dummy_SWE + dummy_ARM + dummy_AZE + dummy_BLR + dummy_EST + dummy_GEO + dummy_KAZ + dummy_LTU + dummy_LVA + dummy_MDA + dummy_TJK + dummy_TKM + dummy_UKR + dummy_UZB + dummy_ARE + dummy_BHR + dummy_CYP + dummy_IRQ + dummy_ISR + dummy_JOR + dummy_KWT + dummy_LBN + dummy_OMN + dummy_QAT + dummy_SAU + dummy_TUR + dummy_AFG + dummy_BGD + dummy_BTN + dummy_IND + dummy_LKA + dummy_MDV + dummy_NPL + dummy_PAK + dummy_CHN + dummy_JPN + dummy_MNG + dummy_IDN + dummy_KHM + dummy_MMR + dummy_MYS + dummy_PHL + dummy_SGP + dummy_THA + dummy_TLS + dummy_VNM + dummy_AUS + dummy_FJI + dummy_GUM + dummy_NCL + dummy_NZL + dummy_PNG + dummy_PYF + dummy_SLB + dummy_TON + dummy_VUT + dummy_WSM + dummy_ABW + dummy_ARG + dummy_BLZ + dummy_BOL + dummy_BRA + dummy_BRB + dummy_CHL + dummy_COL + dummy_CRI + dummy_CUB + dummy_DOM + dummy_ECU + dummy_GRD + dummy_GTM + dummy_GUY + dummy_HND + dummy_HTI + dummy_JAM + dummy_MEX + dummy_NIC + dummy_PAN + dummy_PER + dummy_PRI + dummy_PRY + dummy_SLV + dummy_SUR + dummy_URY + dummy_1990 + dummy_1995 + dummy_2000 + dummy_2005, data = df)

welfare_mod <- lm(value ~ safety_net_2000_y + dummy_CAN + dummy_USA + dummy_AGO + dummy_BDI + dummy_BEN + dummy_BFA + dummy_BWA + dummy_CAF + dummy_CMR + dummy_COM + dummy_DJI + dummy_DZA + dummy_ERI + dummy_ETH + dummy_GAB + dummy_GHA + dummy_GIN + dummy_GNB + dummy_GNQ + dummy_KEN + dummy_LBR + dummy_LBY + dummy_LSO + dummy_MAR + dummy_MDG + dummy_MLI + dummy_MOZ + dummy_MRT + dummy_MUS + dummy_MWI + dummy_NAM + dummy_NER + dummy_NGA + dummy_RWA + dummy_SDN + dummy_SEN + dummy_SLE + dummy_SOM + dummy_SSD + dummy_SWZ + dummy_TCD + dummy_TGO + dummy_TUN + dummy_TZA + dummy_UGA + dummy_ZAF + dummy_ZMB + dummy_ZWE + dummy_ALB + dummy_AUT + dummy_BEL + dummy_BGR + dummy_CHE + dummy_CHI + dummy_CZE + dummy_DEU + dummy_DNK + dummy_ESP + dummy_FIN + dummy_FRA + dummy_GBR + dummy_GRC + dummy_HRV + dummy_HUN + dummy_IRL + dummy_ISL + dummy_ITA + dummy_LUX + dummy_MLT + dummy_MNE + dummy_NLD + dummy_NOR + dummy_POL + dummy_PRT + dummy_ROU + dummy_SRB + dummy_SVN + dummy_SWE + dummy_ARM + dummy_AZE + dummy_BLR + dummy_EST + dummy_GEO + dummy_KAZ + dummy_LTU + dummy_LVA + dummy_MDA + dummy_TJK + dummy_TKM + dummy_UKR + dummy_UZB + dummy_ARE + dummy_BHR + dummy_CYP + dummy_IRQ + dummy_ISR + dummy_JOR + dummy_KWT + dummy_LBN + dummy_OMN + dummy_QAT + dummy_SAU + dummy_TUR + dummy_AFG + dummy_BGD + dummy_BTN + dummy_IND + dummy_LKA + dummy_MDV + dummy_NPL + dummy_PAK + dummy_CHN + dummy_JPN + dummy_MNG + dummy_IDN + dummy_KHM + dummy_MMR + dummy_MYS + dummy_PHL + dummy_SGP + dummy_THA + dummy_TLS + dummy_VNM + dummy_AUS + dummy_FJI + dummy_GUM + dummy_NCL + dummy_NZL + dummy_PNG + dummy_PYF + dummy_SLB + dummy_TON + dummy_VUT + dummy_WSM + dummy_ABW + dummy_ARG + dummy_BLZ + dummy_BOL + dummy_BRA + dummy_BRB + dummy_CHL + dummy_COL + dummy_CRI + dummy_CUB + dummy_DOM + dummy_ECU + dummy_GRD + dummy_GTM + dummy_GUY + dummy_HND + dummy_HTI + dummy_JAM + dummy_MEX + dummy_NIC + dummy_PAN + dummy_PER + dummy_PRI + dummy_PRY + dummy_SLV + dummy_SUR + dummy_URY + dummy_1990 + dummy_1995 + dummy_2000 + dummy_2005, data = df)

tidy(fertility_mod)
tidy(labor_mod)
tidy(literacy_mod)
tidy(enroll_mod)
tidy(age_mod)
tidy(gdp_mod)
tidy(welfare_mod)
```
Literacy (1990), safety net (2000), per workder GDP (1990) are significant at this point.

Need to handle the time and also do differences for the variables. Find a different var for welfare. Do the interaction terms factor regressions.
